version: '3.7'

services:
  elasticsearch:
      image: nshou/elasticsearch-kibana
      ports:
        - "9200:9200"
        - "5601:5601"
      environment:
        SSL_MODE: false
      networks:
        backend:
          aliases:
            - elasticsearch:kibana7
  ui:
      build:
        context: .
        dockerfile: Dockerfile.dev
      command: 
        - ui 
        - -c 
        - /etc/finala/config.yaml
      volumes:
          - ./configuration/ui.yaml:/etc/finala/config.yaml
      ports:
        - "8080:8080"
      networks:
        - backend
      depends_on: 
        - api
  api:
      build:
        context: .
        dockerfile: Dockerfile.dev
      command: 
        - api 
        - -c 
        - /etc/finala/config.yaml
      environment:
        - OVERRIDE_STORAGE_ENDPOINT=http://elasticsearch:9200
      volumes:
          - ./configuration/api.yaml:/etc/finala/config.yaml
      ports:
        - "8081:8081"
      depends_on: 
        - elasticsearch
      networks:
        backend:
          aliases:
            - api
  collector:
      build:
        context: .
        dockerfile: Dockerfile.dev
      command: 
        - collector 
        - -c 
        - /etc/finala/config.yaml
      environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - OVERRIDE_API_ENDPOINT=http://api:8081
      volumes:
          - ./configuration/collector.yaml:/etc/finala/config.yaml
      networks:
        - backend
      depends_on: 
        - api
  # Uncomment the notifier after a first successful run of the Collector
  # notifier:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile.dev
  #     command: 
  #       - notifier 
  #       - -c 
  #       - /etc/finala/config.yaml
  #     volumes:
  #         - ./configuration/notifier.yaml:/etc/finala/config.yaml
  #     networks:
  #       - backend
  #     depends_on: 
  #       - api
 
networks:
  backend:
